using System.Security;
using System.Text;
using System.Text.Json;
using HaselCommon.TranslationGenerator.Utils;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace HaselCommon.TranslationGenerator;

[Generator]
public class TranslationGenerator : IIncrementalGenerator
{
    private const string AttributeName = "HaselCommon.Translations.TranslationSourceAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var additionalFiles = context.AdditionalTextsProvider.Collect();

        var sourceInfo = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeName,
            static (node, _) => node is ClassDeclarationSyntax,
            static (ctx, _) => {
                ctx.Attributes[0].TryGetConstructorArgument(0, out string? filename);
                return new { Symbol = ctx.TargetSymbol as INamedTypeSymbol, Filename = filename };
            })
            .Combine(additionalFiles)
            .Select(static (combined, cancellationToken) => {
                var (info, allFiles) = combined;

                if (info.Symbol == null || string.IsNullOrEmpty(info.Filename))
                    return null;

                var file = allFiles.FirstOrDefault(file => file.Path.EndsWith(info.Filename, StringComparison.OrdinalIgnoreCase));
                if (file == null)
                    return null;

                var content = file.GetText(cancellationToken)?.ToString();
                if (content == null)
                    return null;

                var translations = JsonSerializer.Deserialize<Dictionary<string, Dictionary<string, string>>>(content);
                if (translations == null)
                    return null;

                return new SourceRecord(info.Symbol, translations);
            })
            .Where(static info => info != null)!;

        context.RegisterSourceOutput(sourceInfo,
            static (sourceContext, item) => { sourceContext.AddSource($"{item!.FullyQualifiedMetadataName}.Translations.g.cs", RenderTranslations(item)); });
    }

    private static string RenderTranslations(SourceRecord item)
    {
        var writer = new IndentedTextWriter();

        writer.WriteLine("// <auto-generated>");
        writer.WriteLine();
        writer.WriteLine("using System;");
        writer.WriteLine("using System.Collections.Generic;");
        writer.WriteLine("using System.Text;");
        writer.WriteLine("using Dalamud.Game.Text.Evaluator;");
        writer.WriteLine("using Dalamud.Plugin.Services;");
        writer.WriteLine("using HaselCommon;");
        writer.WriteLine("using HaselCommon.Services;");
        writer.WriteLine("using Lumina.Text.ReadOnly;");
        writer.WriteLine("using Microsoft.Extensions.DependencyInjection;");
        writer.WriteLine();
        writer.WriteLine($"namespace {item.Symbol.ContainingNamespace};");
        writer.WriteLine();
        writer.WriteLine("[RegisterSingleton]");
        writer.WriteLine("[RegisterSingleton<ITranslationProvider>(Duplicate = DuplicateStrategy.Append)]");
        writer.WriteLine($"public partial class {item.Symbol.Name} : ITranslationProvider");

        using (writer.WriteBlock())
        {
            writer.WriteLine("protected readonly IServiceProvider _serviceProvider;");
            writer.WriteLine("protected readonly ISeStringEvaluator _seStringEvaluator;");
            writer.WriteLine("protected readonly LanguageProvider _languageProvider;");
            writer.WriteLine();
            writer.WriteLine($"public {item.Symbol.Name}(IServiceProvider serviceProvider)");

            using (writer.WriteBlock())
            {
                writer.WriteLine("_serviceProvider = serviceProvider;");
                writer.WriteLine("_seStringEvaluator = serviceProvider.GetRequiredService<ISeStringEvaluator>();");
                writer.WriteLine("_languageProvider = serviceProvider.GetRequiredService<LanguageProvider>();");
            }

            writer.WriteLine();
            GenerateTryGetTranslation(writer, item.Translations);
            GenerateMacroStringCache(writer, item.Translations);
            GenerateStringProperties(writer, item.Translations);
            GenerateEvaluateFunctions(writer, item.Translations);
        }

        return writer.ToString() + "\n";
    }

    private static void GenerateTryGetTranslation(in IndentedTextWriter writer, in Dictionary<string, Dictionary<string, string>> translations)
    {
        writer.WriteLine($@"public bool TryGetTranslation(string key, out string text)");

        using (writer.WriteBlock())
        {
            writer.WriteLine("switch (key)");
            using (writer.WriteBlock())
            {
                foreach (var kv in translations)
                {
                    writer.WriteLine($@"case ""{kv.Key}"":");
                    writer.IncreaseIndent();
                    writer.WriteLine($@"text = {MakeSafeIdentifier(kv.Key)};");
                    writer.WriteLine("return true;");
                    writer.DecreaseIndent();
                }

                writer.WriteLine("default:");
                writer.IncreaseIndent();
                writer.WriteLine("text = string.Empty;");
                writer.WriteLine("return false;");
                writer.DecreaseIndent();
            }
        }
    }

    private static void GenerateMacroStringCache(in IndentedTextWriter writer, in Dictionary<string, Dictionary<string, string>> translations)
    {
        foreach (var kv in translations)
        {
            if (!kv.Value.ContainsKey("_isSeString"))
                continue;

            writer.WriteLine();
            writer.WriteLine($"private readonly Dictionary<Language, ReadOnlySeString> {MakeSafeIdentifier(kv.Key)}MacroStringCache = new() {{");
            writer.IncreaseIndent();

            foreach (var entry in kv.Value)
            {
                if (entry.Key == "_isSeString")
                    continue;

                if (!TryGetLanguage(entry.Key, out var language))
                    continue;

                writer.WriteLine($"[Language.{language}] = ReadOnlySeString.FromMacroString({GetStringLiteral(entry.Value, true)}),");
            }

            writer.DecreaseIndent();
            writer.WriteLine("};");
        }
    }

    private static void GenerateStringProperties(in IndentedTextWriter writer, in Dictionary<string, Dictionary<string, string>> translations)
    {
        foreach (var kv in translations)
        {
            GenerateStringProperty(writer, kv);
        }
    }

    private static void GenerateStringProperty(in IndentedTextWriter writer, in KeyValuePair<string, Dictionary<string, string>> translation)
    {
        var propertyName = MakeSafeIdentifier(translation.Key);

        writer.WriteLine();
        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// <c>{translation.Key}</c><br/>");
        writer.WriteLine("/// <list type=\"table\">");

        foreach (var entry in translation.Value)
        {
            if (entry.Key == "_isSeString")
                continue;

            if (!TryGetLanguage(entry.Key, out var language))
                continue;

            writer.WriteLine("///   <item>");
            writer.WriteLine($"///     <term>{language}</term>");
            writer.WriteLine($"///     <description>");
            writer.WriteLine(string.Join("\r\n", SecurityElement.Escape(entry.Value).Replace("*/", "* /").Split('\n').Select(l => $"///          {l}")), true);
            writer.WriteLine($"///     </description>");
            writer.WriteLine("///   </item>");
        }

        writer.WriteLine("/// </list>");
        writer.WriteLine("/// </summary>");

        if (translation.Value.Count > 1)
        {
            writer.WriteLine($@"public string {propertyName} => _languageProvider.Language switch");

            writer.WriteLine("{");
            writer.IncreaseIndent();

            string? defaultTextLiteral = null;

            foreach (var entry in translation.Value)
            {
                if (entry.Key == "_isSeString")
                    continue;

                var langCode = entry.Key;
                var text = entry.Value;
                var stringLiteral = GetStringLiteral(text);

                if (langCode == "en")
                {
                    defaultTextLiteral = stringLiteral;
                    continue;
                }

                if (!TryGetLanguage(langCode, out var language))
                    continue;

                writer.WriteLine($@"Language.{language} => {stringLiteral},");
            }

            writer.WriteLine($@"_ => {defaultTextLiteral ?? "string.Empty"}");

            writer.DecreaseIndent();
            writer.Write("}");

            writer.WriteLine(";");
        }
        else
        {
            writer.Write($@"public string {propertyName} => ");

            foreach (var entry in translation.Value)
            {
                if (entry.Key == "_isSeString")
                    continue;

                writer.WriteLine($@"{GetStringLiteral(entry.Value)};");
            }
        }
    }

    private static void GenerateEvaluateFunctions(in IndentedTextWriter writer, in Dictionary<string, Dictionary<string, string>> translations)
    {
        foreach (var kv in translations)
        {
            if (!kv.Value.ContainsKey("_isSeString"))
                continue;

            var propertyName = MakeSafeIdentifier(kv.Key);

            writer.WriteLine();
            writer.WriteLine("/// <summary>");
            writer.WriteLine($"/// <c>{kv.Key}</c><br/>");
            writer.WriteLine("/// <list type=\"table\">");

            foreach (var entry in kv.Value)
            {
                if (entry.Key == "_isSeString")
                    continue;

                if (!TryGetLanguage(entry.Key, out var language))
                    continue;

                writer.WriteLine("///   <item>");
                writer.WriteLine($"///     <term>{language}</term>");
                writer.WriteLine($"///     <description>");
                writer.Write(SecurityElement.Escape(entry.Value).Replace("*/", "* /"));
                writer.WriteLine($"///     </description>");
                writer.WriteLine("///   </item>");
            }

            writer.WriteLine("/// </list>");
            writer.WriteLine("/// </summary>");

            writer.WriteLine($@"public ReadOnlySeString Evaluate{propertyName}(params SeStringParameter[] parameters)");

            using (writer.WriteBlock())
            {
                writer.WriteLine("var language = _languageProvider.Language;");
                writer.WriteLine();
                writer.WriteLine($"if (!{propertyName}MacroStringCache.TryGetValue(_languageProvider.Language, out var text))");

                using (writer.WriteBlock())
                {
                    writer.WriteLine($"if (!{propertyName}MacroStringCache.TryGetValue(Language.English, out text))");
                    writer.IncreaseIndent();
                    writer.WriteLine("return default;");
                    writer.DecreaseIndent();
                    writer.WriteLine();
                    writer.WriteLine("language = Language.English;");
                }

                writer.WriteLine();
                writer.WriteLine("return _seStringEvaluator.Evaluate(text, parameters, language.ToClientLanguage());");
            }
        }
    }

    private static bool TryGetLanguage(string langCode, out string language)
    {
        language = langCode switch
        {
            "en" => "English",
            "de" => "German",
            "ja" => "Japanese",
            "fr" => "French",
            "it" => "Italian",
            "es" => "Spanish",
            "ko" => "Korean",
            "no" => "Norwegian",
            "ru" => "Russian",
            "zh" => "ChineseSimplified",
            "tw" => "ChineseTraditional",
            _ => string.Empty
        };

        return !string.IsNullOrEmpty(language);
    }

    private static string MakeSafeIdentifier(string key)
    {
        var sb = new StringBuilder();
        foreach (var c in key)
        {
            if (char.IsLetterOrDigit(c) || c == '_')
                sb.Append(c);
            else
                sb.Append('_');
        }
        return sb.ToString();
    }

    private static string GetStringLiteral(string input, bool isUtf8 = false)
    {
        var sb = new StringBuilder();
        sb.Append('"');

        foreach (var c in input)
        {
            switch (c)
            {
                case '\\': sb.Append(@"\\"); break;
                case '\"': sb.Append("\\\""); break;
                case '\n': sb.Append(@"\n"); break;
                case '\r': sb.Append(@"\r"); break;
                case '\t': sb.Append(@"\t"); break;
                default:
                    if (char.IsControl(c))
                    {
                        sb.Append($"\\u{(int)c:x4}");
                    }
                    else
                    {
                        sb.Append(c);
                    }
                    break;
            }
        }

        if (isUtf8)
            sb.Append("\"u8");
        else
            sb.Append("\"");

        return sb.ToString();
    }
}
