namespace HaselCommon.Game.Enums;

public enum TerritoryIntendedUse : byte
{
    Town = 0,
    OpenWorld = 1,
    Inn = 2,
    Dungeon = 3,
    VariantDungeon = 4,
    Jail = 5,
    OpeningArea = 6,
    BeforeTrialDung = 7,
    AllianceRaid = 8,
    OpenWorldInstanceBattle = 9,
    Trial = 10,
    Unknown11 = 11, // unused
    WaitingRoom = 12,
    HousingArea = 13,
    IndoorHousingArea = 14,
    MainStoryQuestPrivateArea = 15,
    Raids = 16,
    RaidFights = 17,
    PvPFrontline = 18,
    Unknown19 = 19, // unused
    ChocoboTutorial = 20,
    Firmament = 21,
    Wedding = 22,
    GoldSaucer = 23,
    Unknown24 = 24, // unused
    LordOfVerminion = 25,
    DiademV1 = 26,
    BeginnerTutorial = 27,
    PvPTheFeast = 28,
    MainStoryQuestEventArea = 29,
    GrandCompanyGarrison = 30,
    DeepDungeon = 31,
    Seasonal = 32, // During the Starlight Celebration, the music in Lower Jeuno will change to a Christmas version.
    TreasureMapInstance = 33,
    SeasonalEventInstancedArea = 34,
    TripleTriadBattlehall = 35,
    ChaoticRaid = 36,
    PvPTheFeastCustomMatch = 37,
    DiademV2 = 38,
    PvPRivalWings = 39,
    Unknown40 = 40,
    Eureka = 41,
    Unknown42 = 42, // unused
    TheCalamityRetold = 43,
    LeapOfFaith = 44,
    MaskedCarnival = 45,
    OceanFishing = 46,
    DiademV3 = 47,
    Bozja = 48,
    IslandSanctuary = 49,
    TripleTriadOpenTournament = 50,
    TripleTriadInvitationalParlor = 51,
    DelubrumReginae = 52,
    DelubrumReginaeSavage = 53,
    Unknown54 = 54, // Propylaion and Ultima Thule?
    Unknown55 = 55, // unused
    Elysion = 56,
    CriterionDungeon = 57,
    CriterionDungeonSavage = 58,
    Blunderville = 59,
    Unknown60 = 60, // unused
    Unknown61 = 61, // unused
    Unknown62 = 62, // unused
};
