using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace HaselCommon.Generator;

[Generator]
public class AddonLifecycleExtensionGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
            "GenerateAddonLifecycleExtensionsAttribute.g.cs", SourceText.From(@"using System;

namespace HaselCommon;

[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
public sealed class GenerateAddonLifecycleExtensionsAttribute : Attribute
{
}
", Encoding.UTF8)));

        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax c && c.AttributeLists.Count > 0,
                transform: static (ctx, _) => GetClassSymbol(ctx))
            .Where(static m => m is not null)
            .Combine(context.CompilationProvider);

        context.RegisterSourceOutput(provider, static (spc, source) => Execute(spc, source.Left!, source.Right));
    }

    private static INamedTypeSymbol? GetClassSymbol(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;

        if (context.SemanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol classSymbol)
            return null;

        foreach (var attr in classSymbol.GetAttributes())
        {
            if (attr.AttributeClass?.Name == "GenerateAddonLifecycleExtensionsAttribute")
            {
                return classSymbol;
            }
        }
        return null;
    }

    private static void Execute(SourceProductionContext spc, INamedTypeSymbol classSymbol, Compilation compilation)
    {
        var addonEventEnum = compilation.GetTypeByMetadataName("Dalamud.Game.Addon.Lifecycle.AddonEvent");

        if (addonEventEnum == null)
            return;

        var className = classSymbol.Name;
        var classNamespace = classSymbol.ContainingNamespace.ToDisplayString();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Dalamud.Game.Addon.Lifecycle;");
        sb.AppendLine("using Dalamud.Game.Addon.Lifecycle.AddonArgTypes;");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {classNamespace};");
        sb.AppendLine();
        sb.AppendLine($"public static partial class {className}");
        sb.AppendLine("{");

        var eventMembers = addonEventEnum.GetMembers()
            .OfType<IFieldSymbol>()
            .Where(f => f.IsConst)
            .Select(f => f.Name)
            .ToList();

        var baseEventNames = eventMembers
            .Select(name => name.StartsWith("Pre") ? name.Substring(3) : (name.StartsWith("Post") ? name.Substring(4) : name))
            .Distinct();

        foreach (var baseName in baseEventNames)
        {
            var argType = GetArgTypeForEvent(baseName);
            sb.AppendLine($"    public delegate void Addon{baseName}Delegate({argType} args);");
        }
        sb.AppendLine();
        sb.AppendLine("    extension(IAddonLifecycle addonLifecycle)");
        sb.Append("    {");

        foreach (var memberName in eventMembers)
        {
            var baseName = memberName.StartsWith("Pre") ? memberName.Substring(3) : (memberName.StartsWith("Post") ? memberName.Substring(4) : memberName);
            var delegateName = $"Addon{baseName}Delegate";
            var argType = GetArgTypeForEvent(baseName);

            sb.AppendLine($@"
        public IDisposable On{memberName}({delegateName} handler, string addonName)
        {{
            return addonLifecycle.RegisterAddonListener<{argType}>(AddonEvent.{memberName}, handler.Invoke, addonName);
        }}");

            sb.AppendLine($@"
        public IDisposable On{memberName}({delegateName} handler, IEnumerable<string> addonNames)
        {{
            return addonLifecycle.RegisterAddonListener<{argType}>(AddonEvent.{memberName}, handler.Invoke, addonNames);
        }}");
        }

        sb.AppendLine(@"
        private IDisposable RegisterAddonListener<TArgs>(AddonEvent eventType, Action<TArgs> handler, string addonName) where TArgs : AddonArgs
        {
            void wrapper(AddonEvent _, AddonArgs args) => handler((TArgs)args);

            return EventExtensions.Subscribe(
                h => addonLifecycle.RegisterListener(eventType, addonName, h),
                h => addonLifecycle.UnregisterListener(eventType, addonName, h),
                (IAddonLifecycle.AddonEventDelegate)wrapper
            );
        }

        private IDisposable RegisterAddonListener<TArgs>(AddonEvent eventType, Action<TArgs> handler, IEnumerable<string> addonNames) where TArgs : AddonArgs
        {
            void wrapper(AddonEvent _, AddonArgs args) => handler((TArgs)args);

            return EventExtensions.Subscribe(
                h => addonLifecycle.RegisterListener(eventType, addonNames, h),
                h => addonLifecycle.UnregisterListener(eventType, addonNames, h),
                (IAddonLifecycle.AddonEventDelegate)wrapper
            );
        }");

        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource($"{className}.AddonLifecycle.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string GetArgTypeForEvent(string baseName) => baseName switch
    {
        "ReceiveEvent" => "AddonReceiveEventArgs",
        "Close" => "AddonCloseArgs",
        "Show" => "AddonShowArgs",
        "Hide" => "AddonHideArgs",
        "Setup" => "AddonSetupArgs",
        "Refresh" => "AddonRefreshArgs",
        "RequestedUpdate" => "AddonRequestedUpdateArgs",
        "FocusChanged" => "AddonFocusChangedArgs",
        _ => "AddonArgs"
    };
}
