using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace HaselCommon.Generator;

[Generator]
public class AgentLifecycleExtensionGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
            "GenerateAgentLifecycleExtensionsAttribute.g.cs", SourceText.From(@"using System;

namespace HaselCommon;

[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
public sealed class GenerateAgentLifecycleExtensionsAttribute : Attribute
{
}
", Encoding.UTF8)));

        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax c && c.AttributeLists.Count > 0,
                transform: static (ctx, _) => GetClassSymbol(ctx))
            .Where(static m => m is not null)
            .Combine(context.CompilationProvider);

        context.RegisterSourceOutput(provider, static (spc, source) => Execute(spc, source.Left!, source.Right));
    }

    private static INamedTypeSymbol? GetClassSymbol(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;

        if (context.SemanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol classSymbol)
            return null;

        foreach (var attr in classSymbol.GetAttributes())
        {
            if (attr.AttributeClass?.Name == "GenerateAgentLifecycleExtensionsAttribute")
            {
                return classSymbol;
            }
        }
        return null;
    }

    private static void Execute(SourceProductionContext spc, INamedTypeSymbol classSymbol, Compilation compilation)
    {
        var agentEventEnum = compilation.GetTypeByMetadataName("Dalamud.Game.Agent.AgentEvent");

        if (agentEventEnum == null)
            return;

        var className = classSymbol.Name;
        var classNamespace = classSymbol.ContainingNamespace.ToDisplayString();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using Dalamud.Game.Agent.AgentArgTypes;");
        sb.AppendLine("using FFXIVClientStructs.FFXIV.Client.UI.Agent;");
        sb.AppendLine("using AgentEvent = Dalamud.Game.Agent.AgentEvent;");
        sb.AppendLine("using DAgentId = Dalamud.Game.Agent.AgentId;");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {classNamespace};");
        sb.AppendLine();
        sb.AppendLine($"public static partial class {className}");
        sb.AppendLine("{");

        var eventMembers = agentEventEnum.GetMembers()
            .OfType<IFieldSymbol>()
            .Where(f => f.IsConst)
            .Select(f => f.Name)
            .ToList();

        var baseEventNames = eventMembers
            .Select(GetBaseEventName)
            .Distinct();

        foreach (var baseName in baseEventNames)
        {
            var argType = GetArgTypeForEvent(baseName);
            sb.AppendLine($"    public delegate void Agent{baseName}Delegate({argType} args);");
        }
        sb.AppendLine();
        sb.AppendLine("    extension(IAgentLifecycle agentLifecycle)");
        sb.Append("    {");

        foreach (var memberName in eventMembers)
        {
            var baseName = GetBaseEventName(memberName);
            var delegateName = $"Agent{baseName}Delegate";
            var argType = GetArgTypeForEvent(baseName);

            sb.AppendLine($@"
        public IDisposable On{memberName}({delegateName} handler, AgentId agentId)
        {{
            return agentLifecycle.RegisterAgentListener<{argType}>(AgentEvent.{memberName}, handler.Invoke, agentId);
        }}");

            sb.AppendLine($@"
        public IDisposable On{memberName}({delegateName} handler, IEnumerable<AgentId> agentIds)
        {{
            return agentLifecycle.RegisterAgentListener<{argType}>(AgentEvent.{memberName}, handler.Invoke, agentIds);
        }}");
        }

        sb.AppendLine(@"
        private IDisposable RegisterAgentListener<TArgs>(AgentEvent eventType, Action<TArgs> handler, AgentId agentId) where TArgs : AgentArgs
        {
            void wrapper(AgentEvent _, AgentArgs args) => handler((TArgs)args);

            return EventExtensions.Subscribe(
                h => agentLifecycle.RegisterListener(eventType, (DAgentId)agentId, h),
                h => agentLifecycle.UnregisterListener(eventType, (DAgentId)agentId, h),
                (IAgentLifecycle.AgentEventDelegate)wrapper
            );
        }

        private IDisposable RegisterAgentListener<TArgs>(AgentEvent eventType, Action<TArgs> handler, IEnumerable<AgentId> agentIds) where TArgs : AgentArgs
        {
            void wrapper(AgentEvent _, AgentArgs args) => handler((TArgs)args);

            return EventExtensions.Subscribe(
                h => agentLifecycle.RegisterListener(eventType, agentIds.Select(id => (DAgentId)id), h),
                h => agentLifecycle.UnregisterListener(eventType, agentIds.Select(id => (DAgentId)id), h),
                (IAgentLifecycle.AgentEventDelegate)wrapper
            );
        }");

        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource($"{className}.AgentLifecycle.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string GetBaseEventName(string memberName)
    {
        var name = memberName;

        if (name.StartsWith("Pre"))
        {
            name = name.Substring(3);
        }
        else if (name.StartsWith("Post"))
        {
            name = name.Substring(4);
        }

        if (name.EndsWith("WithResult"))
        {
            name = name.Substring(0, name.Length - "WithResult".Length);
        }

        return name;
    }

    private static string GetArgTypeForEvent(string baseName) => baseName switch
    {
        "ReceiveEvent" => "AgentReceiveEventArgs",
        "GameEvent" => "AgentGameEventArgs",
        "LevelChange" => "AgentLevelChangeArgs",
        "ClassJobChange" => "AgentClassJobChangeArgs",
        _ => "AgentArgs"
    };
}
