using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace HaselCommon.Generator;

[Generator]
public class EventSubscriberGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
            "GenerateEventSubscribersAttribute.g.cs", SourceText.From(@"using System;

namespace HaselCommon;

[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
public sealed class GenerateEventSubscribersAttribute<T> : Attribute
{
    public Type SourceType { get; } = typeof(T);
}
", Encoding.UTF8)));

        var classProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax c && c.AttributeLists.Count > 0,
                transform: static (ctx, _) => GetClassToGenerate(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(classProvider, static (spc, source) => Execute(spc, source!.Value));
    }

    private static (INamedTypeSymbol ClassSymbol, INamedTypeSymbol TargetInterface)? GetClassToGenerate(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;

        if (context.SemanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol classSymbol)
            return null;

        foreach (var attr in classSymbol.GetAttributes())
        {
            if (attr.AttributeClass is { IsGenericType: true } attrClass
                && attrClass.ConstructedFrom.Name == "GenerateEventSubscribersAttribute"
                && attrClass.TypeArguments.Length == 1
                && attrClass.TypeArguments[0] is INamedTypeSymbol targetType)
            {
                return (classSymbol, targetType);
            }
        }
        return null;
    }

    private static void Execute(SourceProductionContext spc, (INamedTypeSymbol ClassSymbol, INamedTypeSymbol TargetInterface) data)
    {
        var className = data.ClassSymbol.Name;
        var classNamespace = data.ClassSymbol.ContainingNamespace.ToDisplayString();
        var targetTypeName = data.TargetInterface.ToDisplayString();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {classNamespace};");
        sb.AppendLine();
        sb.AppendLine($"public static partial class {className}");
        sb.AppendLine("{");
        sb.AppendLine($"    extension({targetTypeName} source)");
        sb.Append("    {");

        foreach (var evt in data.TargetInterface.GetMembers().OfType<IEventSymbol>())
        {
            var eventName = evt.Name;
            var delegateName = evt.Type.WithNullableAnnotation(NullableAnnotation.NotAnnotated).ToDisplayString();

            sb.AppendLine($@"
        public IDisposable On{eventName}({delegateName} handler)
        {{
            return EventExtensions.Subscribe(
                h => source.{eventName} += h,
                h => source.{eventName} -= h,
                handler);
        }}");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource($"{className}.{data.TargetInterface.Name}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
